name: CI Pipeline

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:


  # ------------------------------------------------------------------------------------------------------------------------

  install:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Clone Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Install Dependencies
        run: composer install

  # ------------------------------------------------------------------------------------------------------------------------

  snippets:
    name: Run PHPUnuhi
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Clone Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Test snippets
        run: php vendor/bin/phpunuhi validate
